// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmrMQirspHMn71PdBHarKUuaU2ZjVh2jU',
    appId: '1:679911738299:web:bd7a2d3da74b19277ad29e',
    messagingSenderId: '679911738299',
    projectId: 'contacts-app-8f821',
    authDomain: 'contacts-app-8f821.firebaseapp.com',
    storageBucket: 'contacts-app-8f821.appspot.com',
    measurementId: 'G-H3RJHS4TZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ01h6Yb_uN_2yAEDlzLU4cIETa-TnaHY',
    appId: '1:679911738299:android:3fd5bf442745f73e7ad29e',
    messagingSenderId: '679911738299',
    projectId: 'contacts-app-8f821',
    storageBucket: 'contacts-app-8f821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAewR-3s-onRQcgKA3ToB7bBGpFikDVBVA',
    appId: '1:679911738299:ios:eaf24e60a70218037ad29e',
    messagingSenderId: '679911738299',
    projectId: 'contacts-app-8f821',
    storageBucket: 'contacts-app-8f821.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAewR-3s-onRQcgKA3ToB7bBGpFikDVBVA',
    appId: '1:679911738299:ios:eaf24e60a70218037ad29e',
    messagingSenderId: '679911738299',
    projectId: 'contacts-app-8f821',
    storageBucket: 'contacts-app-8f821.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmrMQirspHMn71PdBHarKUuaU2ZjVh2jU',
    appId: '1:679911738299:web:7abb731b5305f9217ad29e',
    messagingSenderId: '679911738299',
    projectId: 'contacts-app-8f821',
    authDomain: 'contacts-app-8f821.firebaseapp.com',
    storageBucket: 'contacts-app-8f821.appspot.com',
    measurementId: 'G-FFVDGKZDCN',
  );
}
